### ISSUE TITLE
Make warn command record warning even if no notification is sent

### ISSUE THREAD

**Issue by eritbh** [r-anime/discord-mod-bot#48]
Should be functionally more similar to the ban command, recording the warning reason to the database even if the warning notification can't be sent.

**Comment by bernasx** [comment]
Could we consider a unsent warning section? .note is used for warnings given out verbally already so there's no repetition, and also to just note things down. Using .warn and then writing something they did not receive could be confusing to us. Could be worth debating more with chat mods before implementing

**Comment by Geo1088** [comment]
I could add a flag to stored warnings indicating whether or not they were received. Could be useful for bans as well. Can't hurt to have it even if it's not exposed in `.whois` and is limited to the site.
