### ISSUE TITLE
Include current version/commit information in a command somewhere

### ISSUE THREAD

**Issue by Geo1088** [r-anime/discord-mod-bot#51]
maybe in .ping or .help, or make a new .about command if we have more stuff to put in there

**Comment by Waaiez** [comment]
Thoughts about this?
I'm using the Github API to get the information about this repo then sending it as an embed.
The information does kinda look like a mouthful on mobile but information can always be removed as needed.

Desktop
![Screenshot_20210225_184530](https://user-images.githubusercontent.com/43832467/109186655-d4deb980-7799-11eb-9a00-ceb0cedc5794.png)

Mobile
![Screenshot_2021-02-25-18-45-37-283_com discord](https://user-images.githubusercontent.com/43832467/109186804-f8a1ff80-7799-11eb-9640-5fa8df43f5f5.jpg)

**Comment by Geo1088** [comment]
Hitting the Github API seems a bit overkill to me - the repo description and other metadata like that isn't super useful to most users. All we really need is the current local commit hash and a link to the repo, which we can get pretty easily by invoking Git through `child_process` on startup. I've done something similar in the past which you can check the code for [here](https://github.com/Geo1088/yuuko-bot/blob/39cd12eaad444e5a92b0ac610e4de2aa0cf4c702/commands/about.js#L9-L20) (this code also includes fetching the current latest tag, but I'm not doing tagged releases in this repo).

I think this can all just go in the bottom of the help command rather than being its own new command - we don't really have much "about" information since the bot is pretty strongly associated with the subreddit and only used in one server. I think right now we're using the default help command Yuuko provides, so we'll have to copy-paste that into this repo and then customize it.

**Comment by Waaiez** [comment]
So something like this?
![Screenshot_20210227_180441](https://user-images.githubusercontent.com/43832467/109392705-4cd9ea80-7926-11eb-9db1-1f5246a2b277.png)

**Comment by Geo1088** [comment]
Yeah, that looks great! Feel free to open a PR - I'll do a quick code review and we can get it merged in the next couple days.

**Comment by Geo1088** [comment]
Fixed with #96
