### ISSUE TITLE
allow more human-like syntax for the .convert command

### ISSUE THREAD

**Issue by seanbreckenridge** [r-anime/discord-mod-bot#78]
Not a high priority issue, based on the conversation in the `#tech` channel [here](https://discord.com/channels/267799767843602452/375914227371606016/784730987120295936)

Its common on the server for people to get the .convert syntax wrong, by having the first unit as part of the first token, or adding a 'to' or 'from' in the middle, as a person would when speaking.

Like:

`.convert 10USD EUR`

`.convert 10 USD to EUR`

Perhaps the [function here](https://github.com/r-anime/discord-mod-bot/blob/main/bot/commands/misc/convert.js#L29) could remove common tokens like `to` `from` (as long as those arent country codes), and allow either `10USD` or `10 USD` (could probably be handled with a bit of regex)

I would try and submit a PR, but I'm at a bit of a blank on how to test this, havent used `node` that extensively

Just an issue to keep track of this complaint/perhaps someone is able to PR this

**Comment by sukerokushin** [comment]
slightly tangential but being able to use ' and " when converting feet would be nice as well

**Comment by Geo1088** [comment]
Labelling good first issue, but if nobody else feels like trying their hand at this I'll take it whenever my next round of motivation comes up.

**Comment by Geo1088** [comment]
Fixed in #81, will be live on Discord shortly 🎉
